-- Silicon Remind's authoritative PostgreSQL schema.
--
-- UUIDs are generated by the Rust application so the database does not depend
-- on a particular UUID extension. All timestamps represent UTC instants; the
-- PostgreSQL session time zone is set to UTC by the connection adapter.

CREATE TABLE organization_lifecycle (
    org_id text PRIMARY KEY,
    state text NOT NULL,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),

    CONSTRAINT organization_lifecycle_org_id_valid
        CHECK (org_id ~ '^[a-z0-9_-]{3,50}$'),
    CONSTRAINT organization_lifecycle_state_valid
        CHECK (state IN ('active', 'revoked')),
    CONSTRAINT organization_lifecycle_revocation_consistent
        CHECK ((state = 'revoked') = (revoked_at IS NOT NULL)),
    CONSTRAINT organization_lifecycle_update_order
        CHECK (updated_at >= created_at)
);

-- This durable binding separates IAM's stable UUID principal identity from the
-- public global Silicon handle used by Remind and Hook. Revoked rows are
-- tombstones and are deliberately retained after schedule purging.
CREATE TABLE silicon_identities (
    org_id text NOT NULL,
    principal_id uuid NOT NULL,
    silicon_id text,
    state text NOT NULL,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),

    PRIMARY KEY (org_id, principal_id),
    CONSTRAINT silicon_identities_public_id_unique
        UNIQUE (org_id, silicon_id),
    CONSTRAINT silicon_identities_org_fk
        FOREIGN KEY (org_id) REFERENCES organization_lifecycle (org_id),
    CONSTRAINT silicon_identities_org_id_valid
        CHECK (org_id ~ '^[a-z0-9_-]{3,50}$'),
    CONSTRAINT silicon_identities_public_id_valid
        CHECK (
            silicon_id IS NULL
            OR (
                silicon_id ~ '^[a-z0-9_-]{3,50}:[a-z0-9_-]{3,50}$'
                AND split_part(silicon_id, ':', 2) = org_id
            )
        ),
    CONSTRAINT silicon_identities_state_valid
        CHECK (state IN ('active', 'revoked')),
    CONSTRAINT silicon_identities_active_has_public_id
        CHECK (state <> 'active' OR silicon_id IS NOT NULL),
    CONSTRAINT silicon_identities_revocation_consistent
        CHECK ((state = 'revoked') = (revoked_at IS NOT NULL)),
    CONSTRAINT silicon_identities_update_order
        CHECK (updated_at >= created_at)
);

CREATE TABLE schedules (
    id uuid PRIMARY KEY,
    org_id text NOT NULL,
    owner_principal_id uuid NOT NULL,
    silicon_id text NOT NULL,
    reminder_text text NOT NULL,
    timezone text NOT NULL DEFAULT 'UTC',
    schedule_kind text NOT NULL,
    cron_expression text NOT NULL,
    status text NOT NULL DEFAULT 'active',
    next_run_at timestamptz,
    version bigint NOT NULL DEFAULT 1,
    completed_at timestamptz,
    deleted_at timestamptz,
    purge_after timestamptz,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),

    CONSTRAINT schedules_tenant_identity_unique
        UNIQUE (id, org_id, silicon_id),
    CONSTRAINT schedules_org_id_not_blank
        CHECK (org_id ~ '^[a-z0-9_-]{3,50}$'),
    CONSTRAINT schedules_silicon_id_valid
        CHECK (
            silicon_id ~ '^[a-z0-9_-]{3,50}:[a-z0-9_-]{3,50}$'
            AND split_part(silicon_id, ':', 2) = org_id
        ),
    CONSTRAINT schedules_text_not_blank
        CHECK (reminder_text ~ '[^[:space:]]'),
    CONSTRAINT schedules_text_size
        CHECK (octet_length(reminder_text) <= 100000),
    CONSTRAINT schedules_timezone_not_blank
        CHECK (length(btrim(timezone)) BETWEEN 1 AND 255),
    CONSTRAINT schedules_kind_valid
        CHECK (schedule_kind IN ('one_time', 'recurring')),
    CONSTRAINT schedules_five_field_cron
        CHECK (
            length(btrim(cron_expression)) BETWEEN 1 AND 1000
            AND cardinality(
                regexp_split_to_array(btrim(cron_expression), E'\\s+')
            ) = 5
        ),
    CONSTRAINT schedules_status_valid
        CHECK (status IN ('active', 'paused', 'completed')),
    CONSTRAINT schedules_version_positive
        CHECK (version > 0),
    CONSTRAINT schedules_completed_state_consistent
        CHECK ((status = 'completed') = (completed_at IS NOT NULL)),
    CONSTRAINT schedules_only_one_time_completes
        CHECK (completed_at IS NULL OR schedule_kind = 'one_time'),
    CONSTRAINT schedules_terminal_not_due
        CHECK (status <> 'completed' OR next_run_at IS NULL),
    CONSTRAINT schedules_deleted_not_due
        CHECK (deleted_at IS NULL OR next_run_at IS NULL),
    CONSTRAINT schedules_lifecycle_order
        CHECK (
            completed_at IS NULL OR completed_at >= created_at
        ),
    CONSTRAINT schedules_deletion_order
        CHECK (deleted_at IS NULL OR deleted_at >= created_at),
    CONSTRAINT schedules_update_order
        CHECK (updated_at >= created_at),
    CONSTRAINT schedules_retention_consistent
        CHECK (
            (
                completed_at IS NULL
                AND deleted_at IS NULL
                AND purge_after IS NULL
            )
            OR purge_after = (
                CASE
                    WHEN deleted_at IS NOT NULL THEN deleted_at
                    ELSE completed_at
                END
                + interval '3888000 seconds'
            )
        )
);

CREATE TABLE executions (
    id uuid PRIMARY KEY,
    schedule_id uuid NOT NULL,
    org_id text NOT NULL,
    silicon_id text NOT NULL,
    schedule_version bigint NOT NULL,
    schedule_kind text NOT NULL,
    scheduled_for timestamptz NOT NULL,
    reminder_text text NOT NULL,
    timezone text NOT NULL,
    status text NOT NULL DEFAULT 'pending',
    attempt_count integer NOT NULL DEFAULT 0,
    next_attempt_at timestamptz,
    attempted_at timestamptz,
    delivered_at timestamptz,
    hook_event_id uuid,
    failure_reason text,
    lease_owner text,
    lease_expires_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),

    CONSTRAINT executions_schedule_tenant_fk
        FOREIGN KEY (schedule_id, org_id, silicon_id)
        REFERENCES schedules (id, org_id, silicon_id)
        ON DELETE CASCADE,
    CONSTRAINT executions_occurrence_unique
        UNIQUE (schedule_id, scheduled_for),
    CONSTRAINT executions_schedule_version_positive
        CHECK (schedule_version > 0),
    CONSTRAINT executions_schedule_kind_valid
        CHECK (schedule_kind IN ('one_time', 'recurring')),
    CONSTRAINT executions_text_not_blank
        CHECK (reminder_text ~ '[^[:space:]]'),
    CONSTRAINT executions_text_size
        CHECK (octet_length(reminder_text) <= 100000),
    CONSTRAINT executions_timezone_not_blank
        CHECK (length(btrim(timezone)) BETWEEN 1 AND 255),
    CONSTRAINT executions_status_valid
        CHECK (status IN ('pending', 'delivered', 'retrying', 'failed')),
    CONSTRAINT executions_attempt_count_nonnegative
        CHECK (attempt_count >= 0),
    CONSTRAINT executions_attempt_timestamp_consistent
        CHECK ((attempt_count = 0) = (attempted_at IS NULL)),
    CONSTRAINT executions_retry_has_attempt
        CHECK (status <> 'retrying' OR attempt_count > 0),
    CONSTRAINT executions_delivery_consistent
        CHECK (
            (status = 'delivered')
            = (delivered_at IS NOT NULL AND hook_event_id IS NOT NULL)
        ),
    CONSTRAINT executions_nondelivered_has_no_hook_event
        CHECK (status = 'delivered' OR hook_event_id IS NULL),
    CONSTRAINT executions_terminal_not_scheduled
        CHECK (
            status NOT IN ('delivered', 'failed')
            OR next_attempt_at IS NULL
        ),
    CONSTRAINT executions_claimable_is_scheduled
        CHECK (
            status NOT IN ('pending', 'retrying')
            OR next_attempt_at IS NOT NULL
        ),
    CONSTRAINT executions_lease_pair
        CHECK ((lease_owner IS NULL) = (lease_expires_at IS NULL)),
    CONSTRAINT executions_terminal_not_leased
        CHECK (
            status NOT IN ('delivered', 'failed')
            OR (lease_owner IS NULL AND lease_expires_at IS NULL)
        ),
    CONSTRAINT executions_lease_owner_not_blank
        CHECK (
            lease_owner IS NULL
            OR length(btrim(lease_owner)) BETWEEN 1 AND 255
        ),
    CONSTRAINT executions_failure_reason_size
        CHECK (
            failure_reason IS NULL
            OR octet_length(failure_reason) <= 4096
        ),
    CONSTRAINT executions_update_order
        CHECK (updated_at >= created_at)
);

CREATE UNIQUE INDEX executions_hook_event_unique
    ON executions (hook_event_id)
    WHERE hook_event_id IS NOT NULL;

CREATE TABLE hook_destinations (
    id uuid PRIMARY KEY,
    org_id text NOT NULL,
    owner_principal_id uuid NOT NULL,
    silicon_id text NOT NULL,
    endpoint_url_ciphertext bytea NOT NULL,
    endpoint_url_nonce bytea NOT NULL,
    signing_secret_ciphertext bytea NOT NULL,
    signing_secret_nonce bytea NOT NULL,
    encryption_key_version smallint NOT NULL,
    version bigint NOT NULL DEFAULT 1,
    disabled_at timestamptz,
    purge_after timestamptz,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),

    CONSTRAINT hook_destinations_silicon_unique
        UNIQUE (org_id, silicon_id),
    CONSTRAINT hook_destinations_principal_unique
        UNIQUE (org_id, owner_principal_id),
    CONSTRAINT hook_destinations_org_id_valid
        CHECK (org_id ~ '^[a-z0-9_-]{3,50}$'),
    CONSTRAINT hook_destinations_silicon_id_valid
        CHECK (
            silicon_id ~ '^[a-z0-9_-]{3,50}:[a-z0-9_-]{3,50}$'
            AND split_part(silicon_id, ':', 2) = org_id
        ),
    CONSTRAINT hook_destinations_endpoint_ciphertext_present
        CHECK (octet_length(endpoint_url_ciphertext) > 0),
    CONSTRAINT hook_destinations_secret_ciphertext_present
        CHECK (octet_length(signing_secret_ciphertext) > 0),
    CONSTRAINT hook_destinations_aes_gcm_nonce_size
        CHECK (
            octet_length(endpoint_url_nonce) = 12
            AND octet_length(signing_secret_nonce) = 12
        ),
    CONSTRAINT hook_destinations_key_version_positive
        CHECK (encryption_key_version > 0),
    CONSTRAINT hook_destinations_version_positive
        CHECK (version > 0),
    CONSTRAINT hook_destinations_retention_consistent
        CHECK (
            (disabled_at IS NULL AND purge_after IS NULL)
            OR purge_after = disabled_at + interval '3888000 seconds'
        ),
    CONSTRAINT hook_destinations_update_order
        CHECK (updated_at >= created_at)
);

CREATE TABLE idempotency_records (
    id uuid PRIMARY KEY,
    org_id text NOT NULL,
    actor_type text NOT NULL,
    actor_id text NOT NULL,
    operation text NOT NULL,
    target_id uuid,
    idempotency_key text NOT NULL,
    request_hash bytea NOT NULL,
    state text NOT NULL DEFAULT 'reserved',
    response_status smallint,
    response_body jsonb,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    expires_at timestamptz NOT NULL,

    CONSTRAINT idempotency_scope_unique
        UNIQUE NULLS NOT DISTINCT (
            org_id,
            actor_type,
            actor_id,
            operation,
            target_id,
            idempotency_key
        ),
    CONSTRAINT idempotency_org_id_not_blank
        CHECK (length(btrim(org_id)) BETWEEN 1 AND 255),
    CONSTRAINT idempotency_actor_type_valid
        CHECK (actor_type IN ('carbon', 'silicon', 'application', 'service')),
    CONSTRAINT idempotency_actor_id_not_blank
        CHECK (length(btrim(actor_id)) BETWEEN 1 AND 255),
    CONSTRAINT idempotency_operation_not_blank
        CHECK (length(btrim(operation)) BETWEEN 1 AND 255),
    CONSTRAINT idempotency_key_size
        CHECK (length(idempotency_key) BETWEEN 8 AND 255),
    CONSTRAINT idempotency_hash_sha256_size
        CHECK (octet_length(request_hash) = 32),
    CONSTRAINT idempotency_state_valid
        CHECK (state IN ('reserved', 'completed')),
    CONSTRAINT idempotency_response_consistent
        CHECK (
            (state = 'completed')
            = (response_status IS NOT NULL AND response_body IS NOT NULL)
        ),
    CONSTRAINT idempotency_response_status_valid
        CHECK (
            response_status IS NULL
            OR response_status BETWEEN 100 AND 599
        ),
    CONSTRAINT idempotency_expiry_valid
        CHECK (expires_at > created_at),
    CONSTRAINT idempotency_update_order
        CHECK (updated_at >= created_at)
);

CREATE TABLE internal_event_receipts (
    id uuid PRIMARY KEY,
    source text NOT NULL,
    event_id text NOT NULL,
    event_type text NOT NULL,
    org_id text,
    subject_id text,
    payload jsonb NOT NULL,
    payload_hash bytea NOT NULL,
    status text NOT NULL DEFAULT 'pending',
    attempt_count integer NOT NULL DEFAULT 0,
    next_attempt_at timestamptz,
    processed_at timestamptz,
    failure_reason text,
    lease_owner text,
    lease_expires_at timestamptz,
    received_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),

    CONSTRAINT internal_event_source_id_unique
        UNIQUE (source, event_id),
    CONSTRAINT internal_event_source_not_blank
        CHECK (length(btrim(source)) BETWEEN 1 AND 255),
    CONSTRAINT internal_event_id_not_blank
        CHECK (length(btrim(event_id)) BETWEEN 1 AND 255),
    CONSTRAINT internal_event_type_not_blank
        CHECK (length(btrim(event_type)) BETWEEN 1 AND 255),
    CONSTRAINT internal_event_org_id_not_blank
        CHECK (org_id IS NULL OR length(btrim(org_id)) BETWEEN 1 AND 255),
    CONSTRAINT internal_event_subject_not_blank
        CHECK (
            subject_id IS NULL
            OR length(btrim(subject_id)) BETWEEN 1 AND 255
        ),
    CONSTRAINT internal_event_payload_is_object
        CHECK (jsonb_typeof(payload) = 'object'),
    CONSTRAINT internal_event_hash_sha256_size
        CHECK (octet_length(payload_hash) = 32),
    CONSTRAINT internal_event_status_valid
        CHECK (status IN ('pending', 'processing', 'processed', 'failed')),
    CONSTRAINT internal_event_attempt_count_nonnegative
        CHECK (attempt_count >= 0),
    CONSTRAINT internal_event_processed_consistent
        CHECK ((status = 'processed') = (processed_at IS NOT NULL)),
    CONSTRAINT internal_event_pending_schedule_consistent
        CHECK (
            status NOT IN ('pending', 'failed')
            OR next_attempt_at IS NOT NULL
        ),
    CONSTRAINT internal_event_terminal_not_scheduled
        CHECK (status <> 'processed' OR next_attempt_at IS NULL),
    CONSTRAINT internal_event_lease_pair
        CHECK ((lease_owner IS NULL) = (lease_expires_at IS NULL)),
    CONSTRAINT internal_event_processing_has_lease
        CHECK (
            (status = 'processing')
            = (lease_owner IS NOT NULL AND lease_expires_at IS NOT NULL)
        ),
    CONSTRAINT internal_event_failure_reason_size
        CHECK (
            failure_reason IS NULL
            OR octet_length(failure_reason) <= 4096
        ),
    CONSTRAINT internal_event_update_order
        CHECK (updated_at >= received_at)
);

CREATE TABLE audit_records (
    id uuid PRIMARY KEY,
    occurred_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    org_id text,
    actor_type text,
    actor_id text,
    action text NOT NULL,
    resource_type text NOT NULL,
    resource_id text,
    request_id text,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,

    CONSTRAINT audit_actor_pair
        CHECK ((actor_type IS NULL) = (actor_id IS NULL)),
    CONSTRAINT audit_actor_type_valid
        CHECK (
            actor_type IS NULL
            OR actor_type IN (
                'carbon',
                'silicon',
                'application',
                'service',
                'system'
            )
        ),
    CONSTRAINT audit_org_id_not_blank
        CHECK (org_id IS NULL OR length(btrim(org_id)) BETWEEN 1 AND 255),
    CONSTRAINT audit_actor_id_not_blank
        CHECK (actor_id IS NULL OR length(btrim(actor_id)) BETWEEN 1 AND 255),
    CONSTRAINT audit_action_not_blank
        CHECK (length(btrim(action)) BETWEEN 1 AND 255),
    CONSTRAINT audit_resource_type_not_blank
        CHECK (length(btrim(resource_type)) BETWEEN 1 AND 255),
    CONSTRAINT audit_resource_id_not_blank
        CHECK (
            resource_id IS NULL
            OR length(btrim(resource_id)) BETWEEN 1 AND 255
        ),
    CONSTRAINT audit_metadata_is_object
        CHECK (jsonb_typeof(metadata) = 'object')
);
