// Remind production telemetry. Rolling 24h, refreshed when observations arrive.
const subscriptions = {
  summary: { triggers: [{ table: "remindtelemetry" }], mode: "snapshot", sql: "SELECT toInt32(count()) AS requests, toInt32(countIf(record.status_code::Int32 >= 500)) AS server_errors, toInt32(countIf(record.status_code::Int32 >= 400 AND record.status_code::Int32 < 500)) AS client_errors, round(avg(record.duration_ms::Float64), 1) AS avg_ms, round(quantile(0.95)(record.duration_ms::Float64), 1) AS p95_ms FROM remindtelemetry WHERE record.application::String = 'remind' AND event_ts_ms >= toUnixTimestamp(now()) * 1000 - 86400000 AND record.source::String = 'backend' AND record.event::String = 'request_completed'", onTrigger: (json, rows) => ({ ...json, summary: rows }) },
  routes: { triggers: [{ table: "remindtelemetry" }], mode: "snapshot", sql: "SELECT record.method::String AS method, record.route::String AS route, toInt32(count()) AS requests, toInt32(countIf(record.status_code::Int32 >= 500)) AS errors, round(avg(record.duration_ms::Float64), 1) AS avg_ms FROM remindtelemetry WHERE record.application::String = 'remind' AND event_ts_ms >= toUnixTimestamp(now()) * 1000 - 86400000 AND record.source::String = 'backend' AND record.event::String = 'request_completed' GROUP BY method, route ORDER BY requests DESC LIMIT 15", onTrigger: (json, rows) => ({ ...json, routes: rows }) },
  timeline: { triggers: [{ table: "remindtelemetry" }], mode: "snapshot", sql: "SELECT floor(event_ts_ms / 3600000) * 3600000 AS ts, toInt32(count()) AS requests, toInt32(countIf(record.status_code::Int32 >= 500)) AS errors FROM remindtelemetry WHERE record.application::String = 'remind' AND event_ts_ms >= toUnixTimestamp(now()) * 1000 - 86400000 AND record.source::String = 'backend' AND record.event::String = 'request_completed' GROUP BY ts ORDER BY ts", onTrigger: (json, rows) => ({ ...json, timeline: rows }) },
  worker: { triggers: [{ table: "remindtelemetry" }], mode: "snapshot", sql: "SELECT record_id, event_ts_ms AS ts, record.source::String AS source, record.event::String AS event, record.step::String AS step, record.route::String AS route, record.method::String AS method, record.status_code::Nullable(Int32) AS status, record.duration_ms::Nullable(Float64) AS duration, record.success::Nullable(Bool) AS success, record.service_version::String AS version FROM remindtelemetry WHERE record.application::String = 'remind' AND event_ts_ms >= toUnixTimestamp(now()) * 1000 - 86400000 AND record.source::String = 'worker' AND record.event::String = 'heartbeat' ORDER BY event_ts_ms DESC LIMIT 1", onTrigger: (json, rows) => ({ ...json, worker: rows }) },
  recent: { triggers: [{ table: "remindtelemetry" }], mode: "snapshot", sql: "SELECT record_id, event_ts_ms AS ts, record.source::String AS source, record.event::String AS event, record.step::String AS step, record.route::String AS route, record.method::String AS method, record.status_code::Nullable(Int32) AS status, record.duration_ms::Nullable(Float64) AS duration, record.success::Nullable(Bool) AS success, record.service_version::String AS version FROM remindtelemetry WHERE record.application::String = 'remind' AND event_ts_ms >= toUnixTimestamp(now()) * 1000 - 86400000 AND record.source::String = 'backend' AND record.status_code::Int32 >= 400 ORDER BY event_ts_ms DESC LIMIT 30", onTrigger: (json, rows) => ({ ...json, recent: rows }) },
};
export default defineProcessor({
  init: async () => { let json = {}; for (const sub of Object.values(subscriptions)) json = await sub.onTrigger(json, await mission_control.query(sub.sql)); return json; },
  subscriptions,
  tools: {}
});
